import { images } from "@/next.config";
import Head from "next/head";
import React, { useState, useEffect } from "react";
import { Card,CardBody,CardTitle } from "reactstrap";

export default function Home() {
  const [data, Setdata] = useState([]);

  useEffect(() => {
    // データを取得するためのAPIエンドポイント
    const apiUrl = "https://next-training-shopping-api.vercel.app/api/ranking";

    //fetch関数を使ってAPIからデータを取得
    fetch(apiUrl)
      //
      .then((response) => response.json())
      .then((data) => {
        Setdata(data["ranking"]);
        console.log(data);
      })
      .catch((error) => {
        //errorの情報を渡す
        console.log("失敗", error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
        />
      </Head>
      <main>
        <div>
          <h1>List of Items:</h1>
          <ul>
            {data.map((item, index) => (
              <div>
                <li key={index}>{item["rank"]}</li>
                <li key={index}>{item["name"]}</li>
                <li key={index}>{item["price"]}</li>
                <li key={index}>{item["review"]}</li>
                <a href={item["url"]}>{item["url"]}</a>
                <img src={item["images"][0]["thumbnail"]} />
              </div>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
