import Head from "next/head";
import React, { useState, useEffect } from "react";
import {
  Button,
  Card,
  CardBody,
  CardText,
  CardTitle,
  Col,
  Row,
} from "reactstrap";
import styles from "./styles.module.css";

export default function Home() {
  const [data, Setdata] = useState([]);
  const [searchText, setSearchText] = useState("");
  const [favorites, setFavorites] = useState([]);
  const [originalData, setOriginalData] = useState([]);
  const [sortBy, setSortBy] = useState([]);

  const searchHandler = () => {
    // itemオブジェクト内のnameプロパティに入力された検索語が含まれているかどうかをチェック
    //.toLowerCase()を使用して、大文字小文字の区別を無視して検索
    const filteredData = data.filter((item) =>
      item.name.toLowerCase().includes(searchText.toLowerCase())
    );

    // 絞り込まれたアイテムをセットする
    //絞り込まれたアイテムの配列でdataステートを更新するための関数で絞り込まれたアイテムを新しいデータとしてセット
    Setdata(filteredData);
  };

  const clearHandler = () => {
    // 元のデータをdataステートにセット
    Setdata(originalData);
    setSearchText(""); // クリア時に検索テキストもクリア
  };

  const favHandler = (item) => {
    //some メソッドは、配列内の要素のいずれかが指定した条件を満たす場合に true を返す
    //favorites 配列内に同じrankを持つアイテムが存在するかどうかを確認
    const isItemInFavorites = favorites.some(
      (favorite) => favorite.rank === item.rank
    );

    if (isItemInFavorites) {
      // 既にお気に入りに含まれていれば削除
      setFavorites((prevFavorites) =>
        prevFavorites.filter((favorite) => favorite.rank !== item.rank)
      );
    } else {
      // お気に入りに追加
      setFavorites((prevFavorites) => [...prevFavorites, item]);
    }
  };

  const showFavoritesHandler = () => {
    // お気に入りアイテムを表示
    Setdata(favorites);
  };

  const sortPriceHandler = (method) => {
    // クリックされた並び替えの方法に応じて商品をソート
    if (method === "high") {
      const sortedData = [...data].sort((a, b) => b.price - a.price);
      Setdata(sortedData);
    } else if (method === "low") {
      const sortedData = [...data].sort((a, b) => a.price - b.price);
      Setdata(sortedData);
    }
    setSortBy(method); // ステート更新
  };

  const sortReviewHandler = (method) => {
    // クリックされた並び替えの方法に応じて商品をソート
    if (method === "high") {
      const sortedData = [...data].sort((a, b) => b.review - a.review);
      Setdata(sortedData);
    } else if (method === "low") {
      const sortedData = [...data].sort((a, b) => a.review - b.review);
      Setdata(sortedData);
    }
    setSortBy(method); // ステート更新
  };

  useEffect(() => {
    // データを取得するためのAPIエンドポイント
    const apiUrl = "https://next-training-shopping-api.vercel.app/api/ranking";

    //fetch関数を使ってAPIからデータを取得
    fetch(apiUrl)
      //
      .then((response) => response.json())
      .then((data) => {
        Setdata(data["ranking"]);
        setOriginalData(data["ranking"]);
        console.log(data);
      })
      .catch((error) => {
        //errorの情報を渡す
        console.log("失敗", error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>ほしい物リストランキング！！</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
        />
      </Head>
      <main>
        <div>
          <h1>List of Items:</h1>
          <div className={styles["search-container"]}>
            <div className={styles["search-bar"]}>
              <input
                type="text"
                className={styles["search-input"]}
                //searchTextの値が<input>要素の表示される値
                value={searchText}
                //onChange属性は、<input>要素の値が変更されたときに呼び出される関数を指定するためのもの
                //ユーザーが入力を行うたびに、この関数が実行
                //e.target.valueは、入力フィールドの新しい値
                //setSearchText関数を呼び出してsearchTextステートを更新
                //これにより、ユーザーが入力したテキストがsearchTextステートに保存
                onChange={(e) => setSearchText(e.target.value)}
                placeholder="検索..."
              />
              <button
                onClick={searchHandler}
                className={styles["search-button"]}
              >
                検索
              </button>
              <button onClick={clearHandler} className={styles["clear-button"]}>
                クリア
              </button>
              <button
                onClick={showFavoritesHandler}
                className={styles["favorite-button"]}
              >
                お気に入りを表示
              </button>
              <div className={styles.pricesort}>
                {/* e はイベントを表し、ユーザーが何かアクションを起こした場所で（target）、
              そのアクションによって生まれた具体的な情報（value）を取得する*/}
                <select onChange={(e) => sortPriceHandler(e.target.value)}>
                  <option value="">価格並び替え</option>
                  {/* ユーザーがセレクトメニューで「価格が高い順」を選択すると、e.target.value には文字列 "high" */}
                  <option value="high">価格が高い順</option>
                  <option value="low">価格が低い順</option>
                </select>
              </div>
              <div className={styles.pricesort}>
                <select onChange={(e) => sortReviewHandler(e.target.value)}>
                  <option value="">口コミ並び替え</option>
                  <option value="high">口コミが高い順</option>
                  <option value="low">口コミが低い順</option>
                </select>
              </div>
            </div>
          </div>
          {data.map((item, index) => (
            <Row>
              <Col>
                <CardTitle className={styles.rank}>No.{item["rank"]}</CardTitle>
                <Card key={index} className={styles["card"]}>
                  <CardBody className={styles.CardBody}>
                    <CardText className={styles.title}>
                      <a href={item["url"]}>{item["name"]}</a>
                    </CardText>
                    <CardText className={styles["price"]}>
                      ¥{item["price"]}
                    </CardText>
                    <CardText className={styles["review"]}>
                      レビュー：{item["review"]}
                    </CardText>
                    <a href={item["url"]}>この商品のリンクへ</a>
                    <br></br>
                    <Button onClick={() => favHandler(item)}>
                      {favorites.some((favorite) => favorite.rank === item.rank)
                        ? "❤︎"
                        : "♡"}
                    </Button>

                    <div className={styles.item}>
                      <img
                        src={item["images"][0]["thumbnail"]}
                        alt="Thumbnail"
                      />
                    </div>
                  </CardBody>
                </Card>
              </Col>
            </Row>
          ))}
        </div>
      </main>
    </>
  );
}
